name: Healtchchek

on:
  push:
    branches:
      - master

jobs:
  simple_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fspart11.herokuapp.com/health